In [16]:
from numpy import *
val = array([1, 2, 3], float)
for x in val:
    print(x, end=", ")

1.0, 2.0, 3.0, 

In [25]:
val = array([1, 2, 3, 10.5], float)
for x in val:
    print(x)

1.0
2.0
3.0
10.5


In [29]:
val = array([1, 2, 3.5, 'a'])
for x in val:
    print((x), end= " , ")

1 , 2 , 3.5 , a , 

In [30]:
# python(numpy) me list me hetrogeneous data store kr skte h c++ or java me bhi nhi kr skte.

In [ ]:
val = linspace(10, 20, 5)
for x in val:
    print(x, end=" , ")
    
# Range = 20 - 10 = 10
# Gaps = 5 - 1 = 4
# Gap size = 10 / 4 = 2.5

10.0 , 12.5 , 15.0 , 17.5 , 20.0 , 

In [33]:
val = arange(10, 20, 2)
for x in val:
    print(x, end=" , ")

10 , 12 , 14 , 16 , 18 , 

In [42]:
val = logspace(11, 20, 2)     # logspace(start, stop, count)
for x in val:
    print(x, end=" ")
    
# logspace(11, 20, 2) ka matlab
# Start power = 11 → 10¹¹
# Stop power = 20 → 10²⁰
# Total values = 2

# 🔹 Generated Values
# First value = 10¹¹
# Second value = 10²⁰

100000000000.0 1e+20 

In [ ]:
val = zeros(10)    # 10 bar zero print krna
for x in val:
    print(x)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [ ]:
val = ones(10)     # 10 times 1 print krna
for x in val:
    print(x)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [ ]:
val = full(10, 5)    # 10 times 5 print krna
for x in val:
    print(x)

5
5
5
5
5
5
5
5
5
5


In [54]:
zero = array(10)
print(zero)
print("\n")

one = array([1, 2, 3, 4, 5, 6, 7, 8])
print(one)
print("\n")

two = array([[1,2,3], [4,5,6], [7,8,9]])
print(two)

10


[1 2 3 4 5 6 7 8]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
three = array([[[1,2], [4,5]], [[6,7], [8,9]]])
print(three)

[[[1 2]
  [4 5]]

 [[6 7]
  [8 9]]]
